# Notebook-A1 (Data Wrangling-1)

In [1]:
# Import libraries
import pandas as pd
import numpy as np

In [3]:
# Load the dataset into DataFrame
df=pd.read_csv('iris.csv')
df.describe() # Print description of DataFrame

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [4]:
# Print first and last 5 values
print("First 5 values:\n", df.head())
print ("Last 5 values:\n", df.tail())

First 5 values:
    sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
Last 5 values:
      sepal.length  sepal.width  petal.length  petal.width    variety
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [5]:
# Print duplicated values
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
145    False
146    False
147    False
148    False
149    False
Length: 150, dtype: bool

In [6]:
# Print null values true/false
df.isnull()

     sepal.length  sepal.width  petal.length  petal.width  variety
0           False        False         False        False    False
1           False        False         False        False    False
2           False        False         False        False    False
3           False        False         False        False    False
4           False        False         False        False    False
..            ...          ...           ...          ...      ...
145         False        False         False        False    False
146         False        False         False        False    False
147         False        False         False        False    False
148         False        False         False        False    False
149         False        False         False        False    False

[150 rows x 5 columns]

In [7]:
# Print summary of DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [8]:
# Print shape, i.e. rows + columns
df.shape

(150, 5)

In [9]:
# Print null (true/false) values in sepal.length column
df["sepal.length"].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
145    False
146    False
147    False
148    False
149    False
Name: sepal.length, Length: 150, dtype: bool

In [10]:
# Delete/Drop petal.length column
y = df.drop(["petal.length"], axis=1) # axis=1 column. For row, axis=0
print(y)

     sepal.length  sepal.width  petal.width    variety
0             5.1          3.5          0.2     Setosa
1             4.9          3.0          0.2     Setosa
2             4.7          3.2          0.2     Setosa
3             4.6          3.1          0.2     Setosa
4             5.0          3.6          0.2     Setosa
..            ...          ...          ...        ...
145           6.7          3.0          2.3  Virginica
146           6.3          2.5          1.9  Virginica
147           6.5          3.0          2.0  Virginica
148           6.2          3.4          2.3  Virginica
149           5.9          3.0          1.8  Virginica

[150 rows x 4 columns]

In [11]:
# In variety column, replace Setosa with 0 and Virginica with 1
df['variety'].replace(['Setosa', 'Virginica'], [0,1], inplace=True)
print(df)

     sepal.length  sepal.width  petal.length  petal.width variety
0             5.1          3.5           1.4          0.2       0
1             4.9          3.0           1.4          0.2       0
2             4.7          3.2           1.3          0.2       0
3             4.6          3.1           1.5          0.2       0
4             5.0          3.6           1.4          0.2       0
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       1
146           6.3          2.5           5.0          1.9       1
147           6.5          3.0           5.2          2.0       1
148           6.2          3.4           5.4          2.3       1
149           5.9          3.0           5.1          1.8       1

[150 rows x 5 columns]

C:\Users\kesha\AppData\Local\Temp\ipykernel_18472\453579730.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['variety'].replace(['Setosa', 'Virginica'], [0,1], inplace=True)

In [12]:
# Print sum of NULL values in each column
df.isnull().sum()

sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64

---